# Generated by Django 3.0.7 on 2020-06-16 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MainPage.Member')),
            ],
        ),
    ]
