# Generated by Django 3.0.7 on 2020-06-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20200615_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profileimage',
            field=models.ImageField(default='/static/MainPage/Person.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='text',
            field=models.TextField(default='/static/MainPage/Person.png'),
        ),
    ]
