# Generated by Django 3.0.7 on 2020-06-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_auto_20200615_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profileimage',
            field=models.ImageField(default='/Person.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='text',
            field=models.TextField(default="I am a member of the Eastview Science Olympiad Team. It's a really fun time to be a part of the team, the events are great and never are boring. Maybe you should join sometime."),
        ),
    ]
