# Generated by Django 3.0.7 on 2020-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_auto_20200615_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='AccountStatus',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Inactivated', 'Inactivated'), ('Activated', 'Activated'), ('Alumni', 'Alumni')], default='Inactivated', max_length=11),
        ),
        migrations.AddField(
            model_name='member',
            name='Is_Capitan',
            field=models.BooleanField(default=False),
        ),
    ]
