# Generated by Django 3.0.7 on 2020-06-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_auto_20200616_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='awards',
            field=models.ManyToManyField(blank=True, to='MainPage.Award'),
        ),
        migrations.AlterField(
            model_name='member',
            name='events',
            field=models.ManyToManyField(blank=True, to='MainPage.Event'),
        ),
    ]
