# Generated by Django 3.0.7 on 2020-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
